name: Robot Framework CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Docker
        run: |
          docker --version
          docker compose version

      - name: Build Docker Images
        working-directory: docker
        run: docker compose build

      - name: Start Infrastructure
        working-directory: docker
        run: docker compose --profile infra up -d

      - name: Wait for Services
        run: sleep 40

      - name: Run Robot Tests
        working-directory: docker
        run: |
          docker compose run --rm robot \
            --outputdir reports \
            tests/ui/HomePage.robot

      - name: Upload Robot Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-reports
          path: |
            automation/robot-framework/reports/